# Generated by Django 5.2.3 on 2025-06-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_songdedication'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdedication',
            name='album_cover',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='songdedication',
            name='artists',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='songdedication',
            name='song_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
